### PR TITLE
Switch from ufoLib to fontTools.ufoLib

### PR DESCRIPTION
**Pull request by madig**

### CODE REVIEW

**Comment by madig** [comment]
Hm... drop support for python 2.7 and 3.4? :)

**Comment by chrissimpkins** [comment]
Thanks @madig!  I need to revamp the Appveyor CI config settings.  But yes we can do away with PY < 3.5.  I'll get this merged this evening and will push a new release out.  👍

**Comment by anthrotype** [comment]
FWIW, Fonttools dropped support for 3.5 as well

**Comment by chrissimpkins** [comment]
> FWIW, Fonttools dropped support for 3.5 as well

tyvm Cosimo!

**Pull request merged**
