### PR TITLE
Clearer glif error message

### PR DESCRIPTION
**Pull request by madig**
Previously, an error in glyph "a" or "A" could make for a confusing error message.

Fixes https://github.com/source-foundry/ufolint/issues/25.

### CODE REVIEW

**Comment by chrissimpkins** [comment]
On my phone and didn't look at the source.  Misunderstood your issue.  Yes this is great! Thanks Nikolaus.  Will merge this today and push out a new release.

**Comment by madig** [comment]
I admit my wording was misleading.

Maybe I even mislead myself, as inserting errors in glyph "a" in multiple layers gets you this:
```
[FAIL] a test failed with error: Extra content at the end of the document, line 6, column 1 (<string>, line 6)
[FAIL] a test failed with error: Extra content at the end of the document, line 6, column 1 (<string>, line 6)
```

So to be actually clearer, we need a layer indicator.

Maybe we actually need a file indicator, too... conflict markers aren't something you can fix inside an editor, so telling people "Glyph 'a' (layer 'background') failed ..." probably won't help them, they need to open the file itself in a text editor. 🤔

**Comment by madig** [comment]
This would now print e.g.
```
[FAIL] .\test.ufo\glyphs, glyph "a": Test failed with error: Extra content at the end of the document, line 6, column 1 (<string>, line 6)
[FAIL] .\test.ufo\glyphs, glyph "yyxxxyxyx": Test failed with error: Extra content at the end of the document, line 6, column 1 (<string>, line 6)
[FAIL] .\test.ufo\glyphs.test, glyph "a": Test failed with error: Extra content at the end of the document, line 6, column 1 (<string>, line 6)
```

**Comment by chrissimpkins** [comment]
Looks great!  Nice improvement.  Merging and will push out a new release.  Thanks Nikolaus!

**Pull request merged**
